# To be deployed on PHE Kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntbs-live
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ntbs-live
  template:
    metadata:
      labels:
        app: ntbs-live
    spec:
      # Attempts to schedule the second replica's pod on a different node than the first
      # as a way to guard against unexpected node failures
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - ntbs-live
                topologyKey: kubernetes.io/hostname
      containers:
        - name: ntbs-live
          image: "ntbscontainerregistry.azurecr.io/ntbs-service:live"
          imagePullPolicy: Always
          resources:
            limits:
              memory: 2Gi
              cpu: 1000m # Given in milicores, this is 1 core
            requests:
              memory: 2Gi
              cpu: 1000m # Given in milicores, this is 1 core
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: AzureAdOptions__Enabled
              value: "true"
            - name: AzureAdOptions__ClientId
              valueFrom:
                secretKeyRef:
                  name: uat-phe-azuread-options
                  key: clientId
            - name: AzureAdOptions__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: uat-phe-azuread-options
                  key: clientSecret
            - name: AzureAdOptions__Authority
              valueFrom:
                secretKeyRef:
                  name: uat-phe-azuread-options
                  key: authority
            - name: ConnectionStrings__ntbsContext
              valueFrom:
                secretKeyRef:
                  name: live-connection-strings
                  key: db
            - name: ConnectionStrings__ntbsMigratorContext
              valueFrom:
                secretKeyRef:
                  name: live-connection-strings
                  key: db
            - name: ConnectionStrings__keysContext
              valueFrom:
                secretKeyRef:
                  name: live-connection-strings
                  key: db
            - name: ConnectionStrings__auditContext
              valueFrom:
                secretKeyRef:
                  name: live-connection-strings
                  key: audit-db
            - name: ConnectionStrings__migration
              valueFrom:
                secretKeyRef:
                  name: live-connection-strings
                  key: migration
            - name: ConnectionStrings__specimenMatching
              valueFrom:
                secretKeyRef:
                  name: live-connection-strings
                  key: specimen
            - name: ConnectionStrings__reporting
              valueFrom:
                secretKeyRef:
                  name: live-connection-strings
                  key: reporting
            - name: ExternalLinks__ReportingOverview
              value: "https://app.powerbi.com/Redirect?action=OpenApp&appId=8bc06b73-dd87-45ff-8445-164eaa8fb052&ctid=ee4e1499-4a35-4b2e-ad47-5f3cf9de8666"
            - name: ExternalLinks__ClusterReport
              value: "https://app.powerbi.com/groups/me/apps/8bc06b73-dd87-45ff-8445-164eaa8fb052/reports/3740b629-3f2b-4e37-a0a7-db550dff978c/ReportSection?ctid=ee4e1499-4a35-4b2e-ad47-5f3cf9de8666&filter=Cluster%2FClusterId%20eq '<CLUSTER_ID>'"
            - name: MigrationConfig__NtbsEnvironment
              value: "Live"
            - name: Sentry__Environment
              value: live
            - name: KRB5_CLIENT_KTNAME
              value: /krbtab/keytab
            - name: Hangfire__Enabled
              value: "true"
            - name: Hangfire__WorkerCount
              value: "3"
            - name: EnvironmentDescription__ContainsLiveData
              value: "true"
            - name: EnvironmentDescription__IsLiveSystem
              value: "true"
            - name: EnvironmentDescription__DisplayName
              value: "live"
            - name: EnvironmentDescription__EnvironmentName
              value: "phe-live"
          volumeMounts:
            - mountPath: /krbtab
              name: krb-tab
      imagePullSecrets:
        - name: registery-password
        - name: default-dockercfg-bs7wj
      volumes:
        - name: krb-tab
          secret:
            defaultMode: 420
            secretName: ntbs-live-sql-svc
---
apiVersion: v1
kind: Service
metadata:
  name: ntbs-live
  labels:
    app: ntbs-live
spec:
  type: ClusterIP
  ports:
    - name: '8080'
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: ntbs-live
---
# Real live route, connected to ntbs.phe.nhs.uk
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ntbs-live-tls-n3
spec:
  host: ntbs.phe.nhs.uk
  path: /
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: ntbs-live
  port:
    targetPort: 8080
  wildcardPolicy: None
---
# Temp route that allows us to access the app whilst it's not yet available on the real routes
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ntbs-live-hidden
spec:
  host: ntbs-live-hidden.apps.ocp-por.unix.phe.gov.uk
  path: /
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: ntbs-live
---
# Disruption budget makes sure that manual node drains done by k8s admin
# wait for the app to have a pod running on another node before killing it
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ntbs-live-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ntbs-live
