apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntbs-test
spec:
  selector:
    matchLabels:
      app: ntbs-test
  replicas: 1
  template:
    metadata:
      labels:
        app: ntbs-test
    spec:
      containers:
      - name: ntbs-test
        image: "ntbscontainerregistry.azurecr.io/ntbs-service:test"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Staging"
          - name: ConnectionStrings__ntbsContext
            valueFrom:
              secretKeyRef:
                name: test-connection-strings
                key: appDb
          - name: ConnectionStrings__ntbsMigratorContext
            valueFrom:
              secretKeyRef:
                name: test-connection-strings
                key: appDbMigrator
          - name: ConnectionStrings__keysContext
            valueFrom:
              secretKeyRef:
                name: test-connection-strings
                key: appDb
          - name: ConnectionStrings__auditContext
            valueFrom:
              secretKeyRef:
                name: test-connection-strings
                key: auditDb
          - name: ConnectionStrings__reporting
            valueFrom:
              secretKeyRef:
                name: test-connection-strings
                key: reportingDb
          - name: ConnectionStrings__specimenMatching
            valueFrom:
              secretKeyRef:
                name: test-connection-strings
                key: specimenMatchingDb
          - name: ConnectionStrings__migration
            valueFrom:
              secretKeyRef:
                name: test-connection-strings
                key: migrationDb
          - name: AzureAdOptions__ClientId
            valueFrom:
              secretKeyRef:
                name: test-azuread-options
                key: clientId
          - name: AzureAdOptions__ClientSecret
            valueFrom:
              secretKeyRef:
                name: test-azuread-options
                key: clientSecret
          - name: AzureAdOptions__Authority
            valueFrom:
              secretKeyRef:
                name: test-azuread-options
                key: authority
          - name: AzureAdOptions__Enabled
            value: "true"
          - name: LdapSettings__Password
            valueFrom:
              secretKeyRef:
                name: development-ad-sync-credentials
                key: password
          - name: ExternalLinks__ReportingOverview
            value: "https://app.powerbi.com/Redirect?action=OpenApp&appId=e3e5baa2-50f6-42c8-ae97-7c1bd720a204&ctid=dde2b1dd-a61c-4a89-9734-382c1f37630e"
          - name: ExternalLinks__ClusterReport
            value: "https://app.powerbi.com/groups/me/apps/e3e5baa2-50f6-42c8-ae97-7c1bd720a204/reports/639c1990-d44b-45c9-82b2-2fec2f5ce932/ReportSection?ctid=dde2b1dd-a61c-4a89-9734-382c1f37630e&filter=Cluster%2FClusterId%20eq '<CLUSTER_ID>'"
          - name: MigrationConfig__NtbsEnvironment
            value: "Test"
          - name: Sentry__Environment
            value: "test"
          - name: EnvironmentDescription__EnvironmentName
            value: "azure-test"
      imagePullSecrets:
      - name: registry-password
---
apiVersion: v1
kind: Service
metadata:
  name: ntbs-test
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ntbs-test
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ntbs-test
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
spec:
  tls:
    - hosts:
      - ntbs-test.e32846b1ddf0432eb63f.northeurope.aksapp.io
      secretName: phe-ntbs-test-tls
  rules:
  - host: ntbs-test.e32846b1ddf0432eb63f.northeurope.aksapp.io
    http:
      paths:
      - backend:
          serviceName: ntbs-test
          servicePort: 80
        path: /
