FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build

ARG dotnet_cli_home_arg=/tmp/
ENV DOTNET_CLI_HOME=$dotnet_cli_home_arg

RUN apt-get update -yq \
    && apt-get install curl gnupg -yq \
    && curl -sL https://deb.nodesource.com/setup_10.x | bash \
    && apt-get install nodejs -yq

# Install OpenJDK-8
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;
# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME

# Install Chrome
RUN curl https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o /chrome.deb && \
    dpkg -i /chrome.deb || apt-get install -yf && \
    rm /chrome.deb

WORKDIR /ntbs-ui-tests

COPY ./ntbs-ui-tests/package*.json ./
RUN npm ci
RUN node_modules/.bin/selenium-standalone install

WORKDIR /ntbs-service

COPY ./ntbs-service/package*.json ./
RUN npm install

WORKDIR /
COPY ./NuGet.Config ./NuGet.Config
COPY ./EFAuditer ./EFAuditer
COPY ./frontend-dotnetcore ./frontend-dotnetcore
COPY ./ntbs-service ./ntbs-service
COPY ./ntbs-ui-tests ./ntbs-ui-tests

WORKDIR /ntbs-ui-tests

ENV ASPNETCORE_URLS https://localhost:5001
# We would like to run this script from within jenkinsfile, however the volume mount overwrites the directory and hence the selenium installation
# Cache busting taken from http://dev.im-bot.com/docker-select-caching/
# Tech debt ticket raised: NTBS-629
ARG CACHEBUST=1
RUN ./node_modules/.bin/selenium-standalone start & dotnet test
