// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ntbs_service.Models;

namespace ntbs_service.Migrations
{
    [DbContext(typeof(NtbsContext))]
    [Migration("20190905143217_AddPatientTBHistoryFlags")]
    partial class AddPatientTBHistoryFlags
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ntbs_service.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IsoCode");

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.HasKey("CountryId");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            IsoCode = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            CountryId = 2,
                            IsoCode = "AX",
                            Name = "Åland Islands"
                        },
                        new
                        {
                            CountryId = 3,
                            IsoCode = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            CountryId = 4,
                            IsoCode = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            CountryId = 5,
                            IsoCode = "AS",
                            Name = "American Samoa"
                        },
                        new
                        {
                            CountryId = 6,
                            IsoCode = "AD",
                            Name = "Andorra"
                        },
                        new
                        {
                            CountryId = 7,
                            IsoCode = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            CountryId = 8,
                            IsoCode = "AI",
                            Name = "Anguilla"
                        },
                        new
                        {
                            CountryId = 9,
                            IsoCode = "AQ",
                            Name = "Antarctica"
                        },
                        new
                        {
                            CountryId = 10,
                            IsoCode = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            CountryId = 11,
                            IsoCode = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            CountryId = 12,
                            IsoCode = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            CountryId = 13,
                            IsoCode = "AW",
                            Name = "Aruba"
                        },
                        new
                        {
                            CountryId = 14,
                            IsoCode = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            CountryId = 15,
                            IsoCode = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            CountryId = 16,
                            IsoCode = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            CountryId = 17,
                            IsoCode = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            CountryId = 18,
                            IsoCode = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            CountryId = 19,
                            IsoCode = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            CountryId = 20,
                            IsoCode = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            CountryId = 21,
                            IsoCode = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            CountryId = 22,
                            IsoCode = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            CountryId = 23,
                            IsoCode = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            CountryId = 24,
                            IsoCode = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            CountryId = 25,
                            IsoCode = "BM",
                            Name = "Bermuda"
                        },
                        new
                        {
                            CountryId = 26,
                            IsoCode = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            CountryId = 27,
                            IsoCode = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            CountryId = 28,
                            IsoCode = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            CountryId = 29,
                            IsoCode = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            CountryId = 30,
                            IsoCode = "BV",
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            CountryId = 31,
                            IsoCode = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            CountryId = 32,
                            IsoCode = "IO",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            CountryId = 33,
                            IsoCode = "BN",
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            CountryId = 34,
                            IsoCode = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            CountryId = 35,
                            IsoCode = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            CountryId = 36,
                            IsoCode = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            CountryId = 37,
                            IsoCode = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            CountryId = 38,
                            IsoCode = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            CountryId = 39,
                            IsoCode = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            CountryId = 40,
                            IsoCode = "CV",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            CountryId = 41,
                            IsoCode = "KY",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            CountryId = 42,
                            IsoCode = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            CountryId = 43,
                            IsoCode = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            CountryId = 44,
                            IsoCode = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            CountryId = 45,
                            IsoCode = "CN",
                            Name = "China"
                        },
                        new
                        {
                            CountryId = 46,
                            IsoCode = "CX",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            CountryId = 47,
                            IsoCode = "CC",
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            CountryId = 48,
                            IsoCode = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            CountryId = 49,
                            IsoCode = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            CountryId = 50,
                            IsoCode = "CG",
                            Name = "Congo"
                        },
                        new
                        {
                            CountryId = 51,
                            IsoCode = "CD",
                            Name = "Congo, The Democratic Republic of the"
                        },
                        new
                        {
                            CountryId = 52,
                            IsoCode = "CK",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            CountryId = 53,
                            IsoCode = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            CountryId = 54,
                            IsoCode = "CI",
                            Name = "Côte D'ivoire"
                        },
                        new
                        {
                            CountryId = 55,
                            IsoCode = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            CountryId = 56,
                            IsoCode = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            CountryId = 57,
                            IsoCode = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            CountryId = 58,
                            IsoCode = "CZ",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            CountryId = 59,
                            IsoCode = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            CountryId = 60,
                            IsoCode = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            CountryId = 61,
                            IsoCode = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            CountryId = 62,
                            IsoCode = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            CountryId = 63,
                            IsoCode = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            CountryId = 64,
                            IsoCode = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            CountryId = 65,
                            IsoCode = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            CountryId = 66,
                            IsoCode = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            CountryId = 67,
                            IsoCode = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            CountryId = 68,
                            IsoCode = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            CountryId = 69,
                            IsoCode = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            CountryId = 70,
                            IsoCode = "FK",
                            Name = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            CountryId = 71,
                            IsoCode = "FO",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            CountryId = 72,
                            IsoCode = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            CountryId = 73,
                            IsoCode = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            CountryId = 74,
                            IsoCode = "FR",
                            Name = "France"
                        },
                        new
                        {
                            CountryId = 75,
                            IsoCode = "GF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            CountryId = 76,
                            IsoCode = "PF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            CountryId = 77,
                            IsoCode = "TF",
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            CountryId = 78,
                            IsoCode = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            CountryId = 79,
                            IsoCode = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            CountryId = 80,
                            IsoCode = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            CountryId = 81,
                            IsoCode = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            CountryId = 82,
                            IsoCode = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            CountryId = 83,
                            IsoCode = "GI",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            CountryId = 84,
                            IsoCode = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            CountryId = 85,
                            IsoCode = "GL",
                            Name = "Greenland"
                        },
                        new
                        {
                            CountryId = 86,
                            IsoCode = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            CountryId = 87,
                            IsoCode = "GP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            CountryId = 88,
                            IsoCode = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            CountryId = 89,
                            IsoCode = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            CountryId = 90,
                            IsoCode = "GG",
                            Name = "Guernsey"
                        },
                        new
                        {
                            CountryId = 91,
                            IsoCode = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            CountryId = 92,
                            IsoCode = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            CountryId = 93,
                            IsoCode = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            CountryId = 94,
                            IsoCode = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            CountryId = 95,
                            IsoCode = "HM",
                            Name = "Heard Island and Mcdonald Islands"
                        },
                        new
                        {
                            CountryId = 96,
                            IsoCode = "VA",
                            Name = "Holy See (Vatican City State)"
                        },
                        new
                        {
                            CountryId = 97,
                            IsoCode = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            CountryId = 98,
                            IsoCode = "HK",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            CountryId = 99,
                            IsoCode = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            CountryId = 100,
                            IsoCode = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            CountryId = 101,
                            IsoCode = "IN",
                            Name = "India"
                        },
                        new
                        {
                            CountryId = 102,
                            IsoCode = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            CountryId = 103,
                            IsoCode = "IR",
                            Name = "Iran, Islamic Republic of"
                        },
                        new
                        {
                            CountryId = 104,
                            IsoCode = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            CountryId = 105,
                            IsoCode = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            CountryId = 106,
                            IsoCode = "IM",
                            Name = "Isle Of Man"
                        },
                        new
                        {
                            CountryId = 107,
                            IsoCode = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            CountryId = 108,
                            IsoCode = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            CountryId = 109,
                            IsoCode = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            CountryId = 110,
                            IsoCode = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            CountryId = 111,
                            IsoCode = "JE",
                            Name = "Jersey"
                        },
                        new
                        {
                            CountryId = 112,
                            IsoCode = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            CountryId = 113,
                            IsoCode = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            CountryId = 114,
                            IsoCode = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            CountryId = 115,
                            IsoCode = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            CountryId = 116,
                            IsoCode = "KP",
                            Name = "Korea, Democratic People's Republic of"
                        },
                        new
                        {
                            CountryId = 117,
                            IsoCode = "KR",
                            Name = "Korea, Republic of"
                        },
                        new
                        {
                            CountryId = 118,
                            IsoCode = "XK",
                            Name = "Kosovo"
                        },
                        new
                        {
                            CountryId = 119,
                            IsoCode = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            CountryId = 120,
                            IsoCode = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            CountryId = 121,
                            IsoCode = "LA",
                            Name = "Lao People's Democratic Republic"
                        },
                        new
                        {
                            CountryId = 122,
                            IsoCode = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            CountryId = 123,
                            IsoCode = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            CountryId = 124,
                            IsoCode = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            CountryId = 125,
                            IsoCode = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            CountryId = 126,
                            IsoCode = "LY",
                            Name = "Libyan Arab Jamahiriya"
                        },
                        new
                        {
                            CountryId = 127,
                            IsoCode = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            CountryId = 128,
                            IsoCode = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            CountryId = 129,
                            IsoCode = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            CountryId = 130,
                            IsoCode = "MO",
                            Name = "Macao"
                        },
                        new
                        {
                            CountryId = 131,
                            IsoCode = "MK",
                            Name = "Macedonia, The Former Yugoslav Republic of"
                        },
                        new
                        {
                            CountryId = 132,
                            IsoCode = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            CountryId = 133,
                            IsoCode = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            CountryId = 134,
                            IsoCode = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            CountryId = 135,
                            IsoCode = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            CountryId = 136,
                            IsoCode = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            CountryId = 137,
                            IsoCode = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            CountryId = 138,
                            IsoCode = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            CountryId = 139,
                            IsoCode = "MQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            CountryId = 140,
                            IsoCode = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            CountryId = 141,
                            IsoCode = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            CountryId = 142,
                            IsoCode = "YT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            CountryId = 143,
                            IsoCode = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            CountryId = 144,
                            IsoCode = "FM",
                            Name = "Micronesia, Federated States of"
                        },
                        new
                        {
                            CountryId = 145,
                            IsoCode = "MD",
                            Name = "Moldova"
                        },
                        new
                        {
                            CountryId = 146,
                            IsoCode = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            CountryId = 147,
                            IsoCode = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            CountryId = 148,
                            IsoCode = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            CountryId = 149,
                            IsoCode = "MS",
                            Name = "Montserrat"
                        },
                        new
                        {
                            CountryId = 150,
                            IsoCode = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            CountryId = 151,
                            IsoCode = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            CountryId = 152,
                            IsoCode = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            CountryId = 153,
                            IsoCode = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            CountryId = 154,
                            IsoCode = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            CountryId = 155,
                            IsoCode = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            CountryId = 156,
                            IsoCode = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            CountryId = 157,
                            IsoCode = "AN",
                            Name = "Netherlands Antilles"
                        },
                        new
                        {
                            CountryId = 158,
                            IsoCode = "NC",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            CountryId = 159,
                            IsoCode = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            CountryId = 160,
                            IsoCode = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            CountryId = 161,
                            IsoCode = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            CountryId = 162,
                            IsoCode = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            CountryId = 163,
                            IsoCode = "NU",
                            Name = "Niue"
                        },
                        new
                        {
                            CountryId = 164,
                            IsoCode = "NF",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            CountryId = 165,
                            IsoCode = "MP",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            CountryId = 166,
                            IsoCode = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            CountryId = 167,
                            IsoCode = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            CountryId = 168,
                            IsoCode = "  ",
                            Name = "Other"
                        },
                        new
                        {
                            CountryId = 169,
                            IsoCode = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            CountryId = 170,
                            IsoCode = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            CountryId = 171,
                            IsoCode = "PS",
                            Name = "Palestinian Territory, Occupied"
                        },
                        new
                        {
                            CountryId = 172,
                            IsoCode = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            CountryId = 173,
                            IsoCode = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            CountryId = 174,
                            IsoCode = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            CountryId = 175,
                            IsoCode = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            CountryId = 176,
                            IsoCode = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            CountryId = 177,
                            IsoCode = "PN",
                            Name = "Pitcairn"
                        },
                        new
                        {
                            CountryId = 178,
                            IsoCode = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            CountryId = 179,
                            IsoCode = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            CountryId = 180,
                            IsoCode = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            CountryId = 181,
                            IsoCode = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            CountryId = 182,
                            IsoCode = "RE",
                            Name = "Reunion"
                        },
                        new
                        {
                            CountryId = 183,
                            IsoCode = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            CountryId = 184,
                            IsoCode = "RU",
                            Name = "Russian Federation"
                        },
                        new
                        {
                            CountryId = 185,
                            IsoCode = "RW",
                            Name = "Rwanda"
                        },
                        new
                        {
                            CountryId = 186,
                            IsoCode = "BL",
                            Name = "Saint Barthélemy"
                        },
                        new
                        {
                            CountryId = 187,
                            IsoCode = "SH",
                            Name = "Saint Helena"
                        },
                        new
                        {
                            CountryId = 188,
                            IsoCode = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            CountryId = 189,
                            IsoCode = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            CountryId = 190,
                            IsoCode = "MF",
                            Name = "Saint Martin"
                        },
                        new
                        {
                            CountryId = 191,
                            IsoCode = "PM",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            CountryId = 192,
                            IsoCode = "VC",
                            Name = "Saint Vincent and The Grenadines"
                        },
                        new
                        {
                            CountryId = 193,
                            IsoCode = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            CountryId = 194,
                            IsoCode = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            CountryId = 195,
                            IsoCode = "ST",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            CountryId = 196,
                            IsoCode = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            CountryId = 197,
                            IsoCode = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            CountryId = 198,
                            IsoCode = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            CountryId = 199,
                            IsoCode = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            CountryId = 200,
                            IsoCode = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            CountryId = 201,
                            IsoCode = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            CountryId = 202,
                            IsoCode = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            CountryId = 203,
                            IsoCode = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            CountryId = 204,
                            IsoCode = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            CountryId = 205,
                            IsoCode = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            CountryId = 206,
                            IsoCode = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            CountryId = 207,
                            IsoCode = "GS",
                            Name = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            CountryId = 208,
                            IsoCode = "SSD",
                            Name = "South Sudan"
                        },
                        new
                        {
                            CountryId = 209,
                            IsoCode = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            CountryId = 210,
                            IsoCode = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            CountryId = 211,
                            IsoCode = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            CountryId = 212,
                            IsoCode = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            CountryId = 213,
                            IsoCode = "SJ",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            CountryId = 214,
                            IsoCode = "SZ",
                            Name = "Swaziland"
                        },
                        new
                        {
                            CountryId = 215,
                            IsoCode = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            CountryId = 216,
                            IsoCode = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            CountryId = 217,
                            IsoCode = "SY",
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            CountryId = 218,
                            IsoCode = "TW",
                            Name = "Taiwan, Province of China"
                        },
                        new
                        {
                            CountryId = 219,
                            IsoCode = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            CountryId = 220,
                            IsoCode = "TZ",
                            Name = "Tanzania, United Republic of"
                        },
                        new
                        {
                            CountryId = 221,
                            IsoCode = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            CountryId = 222,
                            IsoCode = "TL",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            CountryId = 223,
                            IsoCode = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            CountryId = 224,
                            IsoCode = "TK",
                            Name = "Tokelau"
                        },
                        new
                        {
                            CountryId = 225,
                            IsoCode = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            CountryId = 226,
                            IsoCode = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            CountryId = 227,
                            IsoCode = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            CountryId = 228,
                            IsoCode = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            CountryId = 229,
                            IsoCode = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            CountryId = 230,
                            IsoCode = "TC",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            CountryId = 231,
                            IsoCode = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            CountryId = 232,
                            IsoCode = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            CountryId = 233,
                            IsoCode = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            CountryId = 234,
                            IsoCode = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            CountryId = 235,
                            IsoCode = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            CountryId = 236,
                            IsoCode = "US",
                            Name = "United States"
                        },
                        new
                        {
                            CountryId = 237,
                            IsoCode = "UM",
                            Name = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            CountryId = 238,
                            IsoCode = "-",
                            Name = "Unknown"
                        },
                        new
                        {
                            CountryId = 239,
                            IsoCode = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            CountryId = 240,
                            IsoCode = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            CountryId = 241,
                            IsoCode = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            CountryId = 242,
                            IsoCode = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            CountryId = 243,
                            IsoCode = "VN",
                            Name = "Viet Nam"
                        },
                        new
                        {
                            CountryId = 244,
                            IsoCode = "VG",
                            Name = "Virgin Islands, British"
                        },
                        new
                        {
                            CountryId = 245,
                            IsoCode = "VI",
                            Name = "Virgin Islands, U.S."
                        },
                        new
                        {
                            CountryId = 246,
                            IsoCode = "WF",
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            CountryId = 247,
                            IsoCode = "EH",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            CountryId = 248,
                            IsoCode = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            CountryId = 249,
                            IsoCode = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            CountryId = 250,
                            IsoCode = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("ntbs_service.Models.Ethnicity", b =>
                {
                    b.Property<int>("EthnicityId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasMaxLength(50);

                    b.Property<string>("Label")
                        .HasMaxLength(200);

                    b.Property<int>("Order");

                    b.HasKey("EthnicityId");

                    b.ToTable("Ethnicity");

                    b.HasData(
                        new
                        {
                            EthnicityId = 1,
                            Code = "A",
                            Label = "White British",
                            Order = 16
                        },
                        new
                        {
                            EthnicityId = 2,
                            Code = "B",
                            Label = "White Irish",
                            Order = 17
                        },
                        new
                        {
                            EthnicityId = 3,
                            Code = "C",
                            Label = "Any other White background",
                            Order = 3
                        },
                        new
                        {
                            EthnicityId = 4,
                            Code = "D",
                            Label = "Mixed - White and Black Caribbean",
                            Order = 14
                        },
                        new
                        {
                            EthnicityId = 5,
                            Code = "E",
                            Label = "Mixed - White and Black African",
                            Order = 13
                        },
                        new
                        {
                            EthnicityId = 6,
                            Code = "F",
                            Label = "Mixed - White and Asian",
                            Order = 12
                        },
                        new
                        {
                            EthnicityId = 7,
                            Code = "G",
                            Label = "Any other mixed background",
                            Order = 9
                        },
                        new
                        {
                            EthnicityId = 8,
                            Code = "H",
                            Label = "Indian",
                            Order = 1
                        },
                        new
                        {
                            EthnicityId = 9,
                            Code = "J",
                            Label = "Pakistani",
                            Order = 2
                        },
                        new
                        {
                            EthnicityId = 10,
                            Code = "K",
                            Label = "Bangladeshi",
                            Order = 10
                        },
                        new
                        {
                            EthnicityId = 11,
                            Code = "L",
                            Label = "Any other Asian background",
                            Order = 6
                        },
                        new
                        {
                            EthnicityId = 12,
                            Code = "M",
                            Label = "Black Caribbean",
                            Order = 11
                        },
                        new
                        {
                            EthnicityId = 13,
                            Code = "N",
                            Label = "Black African",
                            Order = 5
                        },
                        new
                        {
                            EthnicityId = 14,
                            Code = "P",
                            Label = "Any other Black Background",
                            Order = 7
                        },
                        new
                        {
                            EthnicityId = 15,
                            Code = "S",
                            Label = "Any other ethnic group",
                            Order = 8
                        },
                        new
                        {
                            EthnicityId = 16,
                            Code = "R",
                            Label = "Chinese",
                            Order = 4
                        },
                        new
                        {
                            EthnicityId = 17,
                            Code = "Z",
                            Label = "Not stated",
                            Order = 15
                        });
                });

            modelBuilder.Entity("ntbs_service.Models.Hospital", b =>
                {
                    b.Property<int>("HospitalId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .HasMaxLength(200);

                    b.HasKey("HospitalId");

                    b.ToTable("Hospital");
                });

            modelBuilder.Entity("ntbs_service.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HospitalId");

                    b.HasKey("NotificationId");

                    b.HasIndex("HospitalId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("ntbs_service.Models.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .HasMaxLength(200);

                    b.HasKey("RegionId");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("ntbs_service.Models.Sex", b =>
                {
                    b.Property<int>("SexId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .HasMaxLength(200);

                    b.HasKey("SexId");

                    b.ToTable("Sex");

                    b.HasData(
                        new
                        {
                            SexId = 1,
                            Label = "Male"
                        },
                        new
                        {
                            SexId = 2,
                            Label = "Female"
                        },
                        new
                        {
                            SexId = 3,
                            Label = "Unknown"
                        });
                });

            modelBuilder.Entity("ntbs_service.Models.Notification", b =>
                {
                    b.HasOne("ntbs_service.Models.Hospital", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .HasConstraintName("FK_Notification_Hospital");

                    b.OwnsOne("ntbs_service.Models.ClinicalTimeline", "ClinicalTimeline", b1 =>
                        {
                            b1.Property<int>("NotificationId");

                            b1.Property<DateTime?>("DeathDate");

                            b1.Property<DateTime?>("DiagnosisDate");

                            b1.Property<bool>("DidNotStartTreatment");

                            b1.Property<bool>("IsPostMortem");

                            b1.Property<DateTime?>("PresentationDate");

                            b1.Property<DateTime?>("SymptomStartDate");

                            b1.Property<DateTime?>("TreatmentStartDate");

                            b1.HasKey("NotificationId");

                            b1.ToTable("ClinicalTimelines");

                            b1.HasOne("ntbs_service.Models.Notification")
                                .WithOne("ClinicalTimeline")
                                .HasForeignKey("ntbs_service.Models.ClinicalTimeline", "NotificationId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("ntbs_service.Models.PatientDetails", "PatientDetails", b1 =>
                        {
                            b1.Property<int>("NotificationId");

                            b1.Property<int?>("CountryId");

                            b1.Property<DateTime?>("Dob");

                            b1.Property<int?>("EthnicityId");

                            b1.Property<string>("FamilyName")
                                .HasMaxLength(35);

                            b1.Property<string>("GivenName")
                                .HasMaxLength(35);

                            b1.Property<string>("NhsNumber")
                                .HasMaxLength(10);

                            b1.Property<bool>("NhsNumberNotKnown");

                            b1.Property<bool>("NoFixedAbode");

                            b1.Property<string>("Postcode");

                            b1.Property<int?>("SexId");

                            b1.Property<bool?>("UkBorn");

                            b1.HasKey("NotificationId");

                            b1.HasIndex("CountryId");

                            b1.HasIndex("EthnicityId");

                            b1.HasIndex("SexId");

                            b1.ToTable("Patients");

                            b1.HasOne("ntbs_service.Models.Country", "Country")
                                .WithMany()
                                .HasForeignKey("CountryId");

                            b1.HasOne("ntbs_service.Models.Ethnicity", "Ethnicity")
                                .WithMany()
                                .HasForeignKey("EthnicityId");

                            b1.HasOne("ntbs_service.Models.Notification")
                                .WithOne("PatientDetails")
                                .HasForeignKey("ntbs_service.Models.PatientDetails", "NotificationId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.HasOne("ntbs_service.Models.Sex", "Sex")
                                .WithMany()
                                .HasForeignKey("SexId");
                        });

                    b.OwnsOne("ntbs_service.Models.PatientTBHistory", "PatientTBHistory", b1 =>
                        {
                            b1.Property<int>("NotificationId");

                            b1.Property<bool>("NotPreviouslyHadTB");

                            b1.Property<int?>("PreviousTBDiagnosisYear");

                            b1.HasKey("NotificationId");

                            b1.ToTable("PatientTBHistories");

                            b1.HasOne("ntbs_service.Models.Notification")
                                .WithOne("PatientTBHistory")
                                .HasForeignKey("ntbs_service.Models.PatientTBHistory", "NotificationId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
