using System.Collections.Generic;
using System.Linq;
using ntbs_service.Models.ReferenceEntities;

namespace ntbs_service.Models.SeedData
{
    public static class Countries
    {
        public static readonly string[] notHighTbOccurenceCountries = new[]
        {
            "Andorra",
            "Australia",
            "Austria",
            "Belgium",
            "Canada",
            "Cyprus",
            "Denmark",
            "Finland",
            "France",
            "Germany",
            "Greece",
            "Greenland",
            "Guernsey",
            "Holy See (Vatican City State)",
            "Iceland",
            "Ireland",
            "Isle Of Man",
            "Italy",
            "Jersey",
            "Liechtenstein",
            "Luxembourg",
            "Monaco",
            "Netherlands",
            "New Zealand",
            "Norway",
            "Portugal",
            "Spain",
            "Sweden",
            "Switzerland",
            "United Kingdom",
            "United States",
            "United States Minor Outlying Islands",
            "Serbia & Montenegro",
            "Yugoslavia",
            "Zaire"
        };

        public static IEnumerable<Country> GetCountriesArray()
        {
            var allCountries = GetAllCountryData().ToList();

            // Set all countries to high occurence and conditionally flag them as low.
            // The vast majority are high occurence.
            allCountries.ForEach(c => c.HasHighTbOccurence = true);


            foreach (var notHighTbCountry in notHighTbOccurenceCountries)
            {
                // If country not found, or duplicate countries found with the name, this will throw an exception.
                // Couldn't come up with a neat strongly typed way of doing this.
                var lowCountry = allCountries.Single(c => c.Name == notHighTbCountry);
                lowCountry.HasHighTbOccurence = false;
            }

            return allCountries;
        }

        private static IEnumerable<Country> GetAllCountryData()
        {
            return new[] {
                new Country { CountryId = 1, Name = "Afghanistan", IsoCode = "AF", ContinentId = 15 },
                new Country { CountryId = 2, Name = "Åland Islands", IsoCode = "AX", ContinentId = 19 },
                new Country { CountryId = 3, Name = "Albania", IsoCode = "AL", ContinentId = 4 },
                new Country { CountryId = 4, Name = "Algeria", IsoCode = "DZ", ContinentId = 9 },
                new Country { CountryId = 5, Name = "American Samoa", IsoCode = "AS", ContinentId = 11 },
                new Country { CountryId = 6, Name = "Andorra", IsoCode = "AD", ContinentId = 19 },
                new Country { CountryId = 7, Name = "Angola", IsoCode = "AO", ContinentId = 17 },
                new Country { CountryId = 8, Name = "Anguilla", IsoCode = "AI", ContinentId = 14 },
                new Country { CountryId = 9, Name = "Antarctica", IsoCode = "AQ", ContinentId = 2 },
                new Country { CountryId = 10, Name = "Antigua and Barbuda", IsoCode = "AG", ContinentId = 14 },
                new Country { CountryId = 11, Name = "Argentina", IsoCode = "AR", ContinentId = 14 },
                new Country { CountryId = 12, Name = "Armenia", IsoCode = "AM", ContinentId = 6 },
                new Country { CountryId = 13, Name = "Aruba", IsoCode = "AW", ContinentId = 14 },
                new Country { CountryId = 14, Name = "Australia", IsoCode = "AU", ContinentId = 11 },
                new Country { CountryId = 15, Name = "Austria", IsoCode = "AT", ContinentId = 19 },
                new Country { CountryId = 16, Name = "Azerbaijan", IsoCode = "AZ", ContinentId = 6 },
                new Country { CountryId = 17, Name = "Bahamas", IsoCode = "BS", ContinentId = 14 },
                new Country { CountryId = 18, Name = "Bahrain", IsoCode = "BH", ContinentId = 7 },
                new Country { CountryId = 19, Name = "Bangladesh", IsoCode = "BD", ContinentId = 15 },
                new Country { CountryId = 20, Name = "Barbados", IsoCode = "BB", ContinentId = 14 },
                new Country { CountryId = 21, Name = "Belarus", IsoCode = "BY", ContinentId = 6 },
                new Country { CountryId = 22, Name = "Belgium", IsoCode = "BE", ContinentId = 19 },
                new Country { CountryId = 23, Name = "Belize", IsoCode = "BZ", ContinentId = 14 },
                new Country { CountryId = 24, Name = "Benin", IsoCode = "BJ", ContinentId = 17 },
                new Country { CountryId = 25, Name = "Bermuda", IsoCode = "BM", ContinentId = 11 },
                new Country { CountryId = 26, Name = "Bhutan", IsoCode = "BT", ContinentId = 15 },
                new Country { CountryId = 27, Name = "Bolivia", IsoCode = "BO", ContinentId = 14 },
                new Country { CountryId = 28, Name = "Bosnia and Herzegovina", IsoCode = "BA", ContinentId = 4 },
                new Country { CountryId = 29, Name = "Botswana", IsoCode = "BW", ContinentId = 17 },
                new Country { CountryId = 30, Name = "Bouvet Island", IsoCode = "BV", ContinentId = 11 },
                new Country { CountryId = 31, Name = "Brazil", IsoCode = "BR", ContinentId = 14 },
                new Country { CountryId = 32, Name = "British Indian Ocean Territory", IsoCode = "IO", ContinentId = 14 },
                new Country { CountryId = 33, Name = "Brunei Darussalam", IsoCode = "BN", ContinentId = 16 },
                new Country { CountryId = 34, Name = "Bulgaria", IsoCode = "BG", ContinentId = 4 },
                new Country { CountryId = 35, Name = "Burkina Faso", IsoCode = "BF", ContinentId = 17 },
                new Country { CountryId = 36, Name = "Burundi", IsoCode = "BI", ContinentId = 17 },
                new Country { CountryId = 37, Name = "Cambodia", IsoCode = "KH", ContinentId = 16 },
                new Country { CountryId = 38, Name = "Cameroon", IsoCode = "CM", ContinentId = 17 },
                new Country { CountryId = 39, Name = "Canada", IsoCode = "CA", ContinentId = 11 },
                new Country { CountryId = 40, Name = "Cape Verde", IsoCode = "CV", ContinentId = 17 },
                new Country { CountryId = 41, Name = "Cayman Islands", IsoCode = "KY", ContinentId = 14 },
                new Country { CountryId = 42, Name = "Central African Republic", IsoCode = "CF", ContinentId = 17 },
                new Country { CountryId = 43, Name = "Chad", IsoCode = "TD", ContinentId = 17 },
                new Country { CountryId = 44, Name = "Chile", IsoCode = "CL", ContinentId = 14 },
                new Country { CountryId = 45, Name = "China", IsoCode = "CN", ContinentId = 5 },
                new Country { CountryId = 46, Name = "Christmas Island", IsoCode = "CX", ContinentId = 11 },
                new Country { CountryId = 47, Name = "Cocos (Keeling) Islands", IsoCode = "CC", ContinentId = 11 },
                new Country { CountryId = 48, Name = "Colombia", IsoCode = "CO", ContinentId = 14 },
                new Country { CountryId = 49, Name = "Comoros", IsoCode = "KM", ContinentId = 17 },
                new Country { CountryId = 50, Name = "Congo", IsoCode = "CG", ContinentId = 17 },
                new Country { CountryId = 51, Name = "Congo, Democratic Republic of the", IsoCode = "CD", ContinentId = 17 },
                new Country { CountryId = 52, Name = "Cook Islands", IsoCode = "CK", ContinentId = 11 },
                new Country { CountryId = 53, Name = "Costa Rica", IsoCode = "CR", ContinentId = 14 },
                new Country { CountryId = 54, Name = "Côte D'ivoire", IsoCode = "CI", ContinentId = 17 },
                new Country { CountryId = 55, Name = "Croatia", IsoCode = "HR", ContinentId = 4 },
                new Country { CountryId = 56, Name = "Cuba", IsoCode = "CU", ContinentId = 14 },
                new Country { CountryId = 57, Name = "Cyprus", IsoCode = "CY", ContinentId = 19 },
                new Country { CountryId = 58, Name = "Czech Republic", IsoCode = "CZ", ContinentId = 4 },
                new Country { CountryId = 59, Name = "Denmark", IsoCode = "DK", ContinentId = 19 },
                new Country { CountryId = 60, Name = "Djibouti", IsoCode = "DJ", ContinentId = 17 },
                new Country { CountryId = 61, Name = "Dominica", IsoCode = "DM", ContinentId = 14 },
                new Country { CountryId = 62, Name = "Dominican Republic", IsoCode = "DO", ContinentId = 14 },
                new Country { CountryId = 63, Name = "Ecuador", IsoCode = "EC", ContinentId = 14 },
                new Country { CountryId = 64, Name = "Egypt", IsoCode = "EG", ContinentId = 9 },
                new Country { CountryId = 65, Name = "El Salvador", IsoCode = "SV", ContinentId = 14 },
                new Country { CountryId = 66, Name = "Equatorial Guinea", IsoCode = "GQ", ContinentId = 17 },
                new Country { CountryId = 67, Name = "Eritrea", IsoCode = "ER", ContinentId = 17 },
                new Country { CountryId = 68, Name = "Estonia", IsoCode = "EE", ContinentId = 6 },
                new Country { CountryId = 69, Name = "Ethiopia", IsoCode = "ET", ContinentId = 17 },
                new Country { CountryId = 70, Name = "Falkland Islands (Malvinas)", IsoCode = "FK", ContinentId = 14 },
                new Country { CountryId = 71, Name = "Faroe Islands", IsoCode = "FO", ContinentId = 19 },
                new Country { CountryId = 72, Name = "Fiji", IsoCode = "FJ", ContinentId = 11 },
                new Country { CountryId = 73, Name = "Finland", IsoCode = "FI", ContinentId = 19 },
                new Country { CountryId = 74, Name = "France", IsoCode = "FR", ContinentId = 19 },
                new Country { CountryId = 75, Name = "French Guiana", IsoCode = "GF", ContinentId = 14 },
                new Country { CountryId = 76, Name = "French Polynesia", IsoCode = "PF", ContinentId = 11 },
                new Country { CountryId = 77, Name = "French Southern Territories", IsoCode = "TF", ContinentId = 11 },
                new Country { CountryId = 78, Name = "Gabon", IsoCode = "GA", ContinentId = 17 },
                new Country { CountryId = 79, Name = "Gambia", IsoCode = "GM", ContinentId = 17 },
                new Country { CountryId = 80, Name = "Georgia", IsoCode = "GE", ContinentId = 6 },
                new Country { CountryId = 81, Name = "Germany", IsoCode = "DE", ContinentId = 19 },
                new Country { CountryId = 82, Name = "Ghana", IsoCode = "GH", ContinentId = 17 },
                new Country { CountryId = 83, Name = "Gibraltar", IsoCode = "GI", ContinentId = 19 },
                new Country { CountryId = 84, Name = "Greece", IsoCode = "GR", ContinentId = 19 },
                new Country { CountryId = 85, Name = "Greenland", IsoCode = "GL", ContinentId = 19 },
                new Country { CountryId = 86, Name = "Grenada", IsoCode = "GD", ContinentId = 14 },
                new Country { CountryId = 87, Name = "Guadeloupe", IsoCode = "GP", ContinentId = 14 },
                new Country { CountryId = 88, Name = "Guam", IsoCode = "GU", ContinentId = 11 },
                new Country { CountryId = 89, Name = "Guatemala", IsoCode = "GT", ContinentId = 14 },
                new Country { CountryId = 90, Name = "Guernsey", IsoCode = "GG", ContinentId = 19 },
                new Country { CountryId = 91, Name = "Guinea", IsoCode = "GN", ContinentId = 17 },
                new Country { CountryId = 92, Name = "Guinea-Bissau", IsoCode = "GW", ContinentId = 17 },
                new Country { CountryId = 93, Name = "Guyana", IsoCode = "GY", ContinentId = 14 },
                new Country { CountryId = 94, Name = "Haiti", IsoCode = "HT", ContinentId = 14 },
                new Country { CountryId = 95, Name = "Heard Island and Mcdonald Islands", IsoCode = "HM", ContinentId = 14 },
                new Country { CountryId = 96, Name = "Holy See (Vatican City State)", IsoCode = "VA", ContinentId = 19 },
                new Country { CountryId = 97, Name = "Honduras", IsoCode = "HN", ContinentId = 14 },
                new Country { CountryId = 98, Name = "Hong Kong", IsoCode = "HK", ContinentId = 5 },
                new Country { CountryId = 99, Name = "Hungary", IsoCode = "HU", ContinentId = 4 },
                new Country { CountryId = 100, Name = "Iceland", IsoCode = "IS", ContinentId = 19 },
                new Country { CountryId = 101, Name = "India", IsoCode = "IN", ContinentId = 15 },
                new Country { CountryId = 102, Name = "Indonesia", IsoCode = "ID", ContinentId = 16 },
                new Country { CountryId = 103, Name = "Iran, Islamic Republic of", IsoCode = "IR", ContinentId = 15 },
                new Country { CountryId = 104, Name = "Iraq", IsoCode = "IQ", ContinentId = 7 },
                new Country { CountryId = 105, Name = "Ireland", IsoCode = "IE", ContinentId = 19 },
                new Country { CountryId = 106, Name = "Isle Of Man", IsoCode = "IM", ContinentId = 19 },
                new Country { CountryId = 107, Name = "Israel", IsoCode = "IL", ContinentId = 7 },
                new Country { CountryId = 108, Name = "Italy", IsoCode = "IT", ContinentId = 19 },
                new Country { CountryId = 109, Name = "Jamaica", IsoCode = "JM", ContinentId = 14 },
                new Country { CountryId = 110, Name = "Japan", IsoCode = "JP", ContinentId = 5 },
                new Country { CountryId = 111, Name = "Jersey", IsoCode = "JE", ContinentId = 19 },
                new Country { CountryId = 112, Name = "Jordan", IsoCode = "JO", ContinentId = 7 },
                new Country { CountryId = 113, Name = "Kazakhstan", IsoCode = "KZ", ContinentId = 6 },
                new Country { CountryId = 114, Name = "Kenya", IsoCode = "KE", ContinentId = 17 },
                new Country { CountryId = 115, Name = "Kiribati", IsoCode = "KI", ContinentId = 11 },
                new Country { CountryId = 116, Name = "Korea, Democratic People's Republic of", IsoCode = "KP", ContinentId = 5 },
                new Country { CountryId = 117, Name = "Korea, Republic of", IsoCode = "KR", ContinentId = 5 },
                new Country { CountryId = 118, Name = "Kosovo", IsoCode = "XK", ContinentId = 4 },
                new Country { CountryId = 119, Name = "Kuwait", IsoCode = "KW", ContinentId = 7 },
                new Country { CountryId = 120, Name = "Kyrgyzstan", IsoCode = "KG", ContinentId = 6 },
                new Country { CountryId = 121, Name = "Lao People's Democratic Republic", IsoCode = "LA", ContinentId = 16 },
                new Country { CountryId = 122, Name = "Latvia", IsoCode = "LV", ContinentId = 6 },
                new Country { CountryId = 123, Name = "Lebanon", IsoCode = "LB", ContinentId = 7 },
                new Country { CountryId = 124, Name = "Lesotho", IsoCode = "LS", ContinentId = 17 },
                new Country { CountryId = 125, Name = "Liberia", IsoCode = "LR", ContinentId = 17 },
                new Country { CountryId = 126, Name = "Libyan Arab Jamahiriya", IsoCode = "LY", ContinentId = 9 },
                new Country { CountryId = 127, Name = "Liechtenstein", IsoCode = "LI", ContinentId = 19 },
                new Country { CountryId = 128, Name = "Lithuania", IsoCode = "LT", ContinentId = 6 },
                new Country { CountryId = 129, Name = "Luxembourg", IsoCode = "LU", ContinentId = 19 },
                new Country { CountryId = 130, Name = "Macao", IsoCode = "MO", ContinentId = 5 },
                new Country { CountryId = 131, Name = "North Macedonia", IsoCode = "MK", ContinentId = 4 },
                new Country { CountryId = 132, Name = "Madagascar", IsoCode = "MG", ContinentId = 17 },
                new Country { CountryId = 133, Name = "Malawi", IsoCode = "MW", ContinentId = 17 },
                new Country { CountryId = 134, Name = "Malaysia", IsoCode = "MY", ContinentId = 16 },
                new Country { CountryId = 135, Name = "Maldives", IsoCode = "MV", ContinentId = 15 },
                new Country { CountryId = 136, Name = "Mali", IsoCode = "ML", ContinentId = 17 },
                new Country { CountryId = 137, Name = "Malta", IsoCode = "MT", ContinentId = 19 },
                new Country { CountryId = 138, Name = "Marshall Islands", IsoCode = "MH", ContinentId = 11 },
                new Country { CountryId = 139, Name = "Martinique", IsoCode = "MQ", ContinentId = 14 },
                new Country { CountryId = 140, Name = "Mauritania", IsoCode = "MR", ContinentId = 17 },
                new Country { CountryId = 141, Name = "Mauritius", IsoCode = "MU", ContinentId = 17 },
                new Country { CountryId = 142, Name = "Mayotte", IsoCode = "YT", ContinentId = 17 },
                new Country { CountryId = 143, Name = "Mexico", IsoCode = "MX", ContinentId = 14 },
                new Country { CountryId = 144, Name = "Micronesia, Federated States of", IsoCode = "FM", ContinentId = 11 },
                new Country { CountryId = 145, Name = "Moldova", IsoCode = "MD", ContinentId = 6 },
                new Country { CountryId = 146, Name = "Monaco", IsoCode = "MC", ContinentId = 19 },
                new Country { CountryId = 147, Name = "Mongolia", IsoCode = "MN", ContinentId = 5 },
                new Country { CountryId = 148, Name = "Montenegro", IsoCode = "ME", ContinentId = 4 },
                new Country { CountryId = 149, Name = "Montserrat", IsoCode = "MS", ContinentId = 14 },
                new Country { CountryId = 150, Name = "Morocco", IsoCode = "MA", ContinentId = 9 },
                new Country { CountryId = 151, Name = "Mozambique", IsoCode = "MZ", ContinentId = 17 },
                new Country { CountryId = 152, Name = "Myanmar", IsoCode = "MM", ContinentId = 16 },
                new Country { CountryId = 153, Name = "Namibia", IsoCode = "NA", ContinentId = 17 },
                new Country { CountryId = 154, Name = "Nauru", IsoCode = "NR", ContinentId = 11 },
                new Country { CountryId = 155, Name = "Nepal", IsoCode = "NP", ContinentId = 15 },
                new Country { CountryId = 156, Name = "Netherlands", IsoCode = "NL", ContinentId = 19 },
                new Country { CountryId = 157, Name = "Netherlands Antilles", IsoCode = "AN", ContinentId = 14 },
                new Country { CountryId = 158, Name = "New Caledonia", IsoCode = "NC", ContinentId = 11 },
                new Country { CountryId = 159, Name = "New Zealand", IsoCode = "NZ", ContinentId = 11 },
                new Country { CountryId = 160, Name = "Nicaragua", IsoCode = "NI", ContinentId = 14 },
                new Country { CountryId = 161, Name = "Niger", IsoCode = "NE", ContinentId = 17 },
                new Country { CountryId = 162, Name = "Nigeria", IsoCode = "NG", ContinentId = 17 },
                new Country { CountryId = 163, Name = "Niue", IsoCode = "NU", ContinentId = 11 },
                new Country { CountryId = 164, Name = "Norfolk Island", IsoCode = "NF", ContinentId = 11 },
                new Country { CountryId = 165, Name = "Northern Mariana Islands", IsoCode = "MP", ContinentId = 11 },
                new Country { CountryId = 166, Name = "Norway", IsoCode = "NO", ContinentId = 19 },
                new Country { CountryId = 167, Name = "Oman", IsoCode = "OM", ContinentId = 7 },
                new Country { CountryId = 168, Name = "Other", IsoCode = "  ", ContinentId = 18 },
                new Country { CountryId = 169, Name = "Pakistan", IsoCode = "PK", ContinentId = 15 },
                new Country { CountryId = 170, Name = "Palau", IsoCode = "PW", ContinentId = 11 },
                new Country { CountryId = 171, Name = "Palestine, State of", IsoCode = "PS", ContinentId = 7 },
                new Country { CountryId = 172, Name = "Panama", IsoCode = "PA", ContinentId = 14 },
                new Country { CountryId = 173, Name = "Papua New Guinea", IsoCode = "PG", ContinentId = 11 },
                new Country { CountryId = 174, Name = "Paraguay", IsoCode = "PY", ContinentId = 14 },
                new Country { CountryId = 175, Name = "Peru", IsoCode = "PE", ContinentId = 14 },
                new Country { CountryId = 176, Name = "Philippines", IsoCode = "PH", ContinentId = 16 },
                new Country { CountryId = 177, Name = "Pitcairn", IsoCode = "PN", ContinentId = 11 },
                new Country { CountryId = 178, Name = "Poland", IsoCode = "PL", ContinentId = 4 },
                new Country { CountryId = 179, Name = "Portugal", IsoCode = "PT", ContinentId = 19 },
                new Country { CountryId = 180, Name = "Puerto Rico", IsoCode = "PR", ContinentId = 14 },
                new Country { CountryId = 181, Name = "Qatar", IsoCode = "QA", ContinentId = 7 },
                new Country { CountryId = 182, Name = "Reunion", IsoCode = "RE", ContinentId = 17 },
                new Country { CountryId = 183, Name = "Romania", IsoCode = "RO", ContinentId = 4 },
                new Country { CountryId = 184, Name = "Russian Federation", IsoCode = "RU", ContinentId = 6 },
                new Country { CountryId = 185, Name = "Rwanda", IsoCode = "RW", ContinentId = 17 },
                new Country { CountryId = 186, Name = "Saint Barthélemy", IsoCode = "BL", ContinentId = 14 },
                new Country { CountryId = 187, Name = "Saint Helena", IsoCode = "SH", ContinentId = 17 },
                new Country { CountryId = 188, Name = "Saint Kitts and Nevis", IsoCode = "KN", ContinentId = 14 },
                new Country { CountryId = 189, Name = "Saint Lucia", IsoCode = "LC", ContinentId = 14 },
                new Country { CountryId = 190, Name = "Saint Martin", IsoCode = "MF", ContinentId = 14 },
                new Country { CountryId = 191, Name = "Saint Pierre and Miquelon", IsoCode = "PM", ContinentId = 11 },
                new Country { CountryId = 192, Name = "Saint Vincent and The Grenadines", IsoCode = "VC", ContinentId = 14 },
                new Country { CountryId = 193, Name = "Samoa", IsoCode = "WS", ContinentId = 11 },
                new Country { CountryId = 194, Name = "San Marino", IsoCode = "SM", ContinentId = 19 },
                new Country { CountryId = 195, Name = "Sao Tome and Principe", IsoCode = "ST", ContinentId = 17 },
                new Country { CountryId = 196, Name = "Saudi Arabia", IsoCode = "SA", ContinentId = 7 },
                new Country { CountryId = 197, Name = "Senegal", IsoCode = "SN", ContinentId = 17 },
                new Country { CountryId = 198, Name = "Serbia", IsoCode = "RS", ContinentId = 4 },
                new Country { CountryId = 199, Name = "Seychelles", IsoCode = "SC", ContinentId = 17 },
                new Country { CountryId = 200, Name = "Sierra Leone", IsoCode = "SL", ContinentId = 17 },
                new Country { CountryId = 201, Name = "Singapore", IsoCode = "SG", ContinentId = 16 },
                new Country { CountryId = 202, Name = "Slovakia", IsoCode = "SK", ContinentId = 4 },
                new Country { CountryId = 203, Name = "Slovenia", IsoCode = "SI", ContinentId = 4 },
                new Country { CountryId = 204, Name = "Solomon Islands", IsoCode = "SB", ContinentId = 11 },
                new Country { CountryId = 205, Name = "Somalia", IsoCode = "SO", ContinentId = 17 },
                new Country { CountryId = 206, Name = "South Africa", IsoCode = "ZA", ContinentId = 17 },
                new Country { CountryId = 207, Name = "South Georgia and the South Sandwich Islands", IsoCode = "GS", ContinentId = 14 },
                new Country { CountryId = 208, Name = "South Sudan", IsoCode = "SSD", ContinentId = 17 },
                new Country { CountryId = 209, Name = "Spain", IsoCode = "ES", ContinentId = 19 },
                new Country { CountryId = 210, Name = "Sri Lanka", IsoCode = "LK", ContinentId = 15 },
                new Country { CountryId = 211, Name = "Sudan", IsoCode = "SD", ContinentId = 9 },
                new Country { CountryId = 212, Name = "Suriname", IsoCode = "SR", ContinentId = 14 },
                new Country { CountryId = 213, Name = "Svalbard and Jan Mayen", IsoCode = "SJ", ContinentId = 19 },
                new Country { CountryId = 214, Name = "Swaziland", IsoCode = "SZ", ContinentId = 17 },
                new Country { CountryId = 215, Name = "Sweden", IsoCode = "SE", ContinentId = 19 },
                new Country { CountryId = 216, Name = "Switzerland", IsoCode = "CH", ContinentId = 19 },
                new Country { CountryId = 217, Name = "Syrian Arab Republic", IsoCode = "SY", ContinentId = 7 },
                new Country { CountryId = 218, Name = "Taiwan, Province of China", IsoCode = "TW", ContinentId = 5 },
                new Country { CountryId = 219, Name = "Tajikistan", IsoCode = "TJ", ContinentId = 6 },
                new Country { CountryId = 220, Name = "Tanzania, United Republic of", IsoCode = "TZ", ContinentId = 17 },
                new Country { CountryId = 221, Name = "Thailand", IsoCode = "TH", ContinentId = 16 },
                new Country { CountryId = 222, Name = "Timor-Leste", IsoCode = "TL", ContinentId = 16 },
                new Country { CountryId = 223, Name = "Togo", IsoCode = "TG", ContinentId = 17 },
                new Country { CountryId = 224, Name = "Tokelau", IsoCode = "TK", ContinentId = 11 },
                new Country { CountryId = 225, Name = "Tonga", IsoCode = "TO", ContinentId = 11 },
                new Country { CountryId = 226, Name = "Trinidad and Tobago", IsoCode = "TT", ContinentId = 14 },
                new Country { CountryId = 227, Name = "Tunisia", IsoCode = "TN", ContinentId = 9 },
                new Country { CountryId = 228, Name = "Turkey", IsoCode = "TR", ContinentId = 4 },
                new Country { CountryId = 229, Name = "Turkmenistan", IsoCode = "TM", ContinentId = 6 },
                new Country { CountryId = 230, Name = "Turks and Caicos Islands", IsoCode = "TC", ContinentId = 14 },
                new Country { CountryId = 231, Name = "Tuvalu", IsoCode = "TV", ContinentId = 11 },
                new Country { CountryId = 232, Name = "Uganda", IsoCode = "UG", ContinentId = 17 },
                new Country { CountryId = 233, Name = "Ukraine", IsoCode = "UA", ContinentId = 6 },
                new Country { CountryId = 234, Name = "United Arab Emirates", IsoCode = "AE", ContinentId = 7 },
                new Country { CountryId = 235, Name = "United Kingdom", IsoCode = Models.Countries.UkCode, ContinentId = 19 },
                new Country { CountryId = 236, Name = "United States", IsoCode = "US", ContinentId = 11 },
                new Country { CountryId = 237, Name = "United States Minor Outlying Islands", IsoCode = "UM", ContinentId = 11 },
                new Country { CountryId = Models.Countries.UnknownId, Name = "Unknown", IsoCode = Models.Countries.UnknownCode, ContinentId = 18 },
                new Country { CountryId = 239, Name = "Uruguay", IsoCode = "UY", ContinentId = 14 },
                new Country { CountryId = 240, Name = "Uzbekistan", IsoCode = "UZ", ContinentId = 6 },
                new Country { CountryId = 241, Name = "Vanuatu", IsoCode = "VU", ContinentId = 11 },
                new Country { CountryId = 242, Name = "Venezuela", IsoCode = "VE", ContinentId = 14 },
                new Country { CountryId = 243, Name = "Viet Nam", IsoCode = "VN", ContinentId = 16 },
                new Country { CountryId = 244, Name = "Virgin Islands, British", IsoCode = "VG", ContinentId = 14 },
                new Country { CountryId = 245, Name = "Virgin Islands, U.S.", IsoCode = "VI", ContinentId = 14 },
                new Country { CountryId = 246, Name = "Wallis and Futuna", IsoCode = "WF", ContinentId = 11 },
                new Country { CountryId = 247, Name = "Western Sahara", IsoCode = "EH", ContinentId = 9 },
                new Country { CountryId = 248, Name = "Yemen", IsoCode = "YE", ContinentId = 7 },
                new Country { CountryId = 249, Name = "Zambia", IsoCode = "ZM", ContinentId = 17 },
                new Country { CountryId = 250, Name = "Zimbabwe", IsoCode = "ZW", ContinentId = 17 },
                new Country { CountryId = 251, Name = "Serbia & Montenegro", IsoCode = "CS", IsLegacy = true, ContinentId = 4 },
                new Country { CountryId = 252, Name = "Yugoslavia", IsoCode = "YU", IsLegacy = true, ContinentId = 4},
                new Country { CountryId = 253, Name = "Zaire", IsoCode = "ZR", IsLegacy = true, ContinentId = 17 }
            };
        }

    }
}
