using System;

namespace ntbs_service.Models
{
    public class SpecimenMatchPairing : IEquatable<SpecimenMatchPairing>
    {
        public string ReferenceLaboratoryNumber { get; set; }
        public int NotificationId { get; set; }

        #region AutoGenerated EqualityMembers
        public bool Equals(SpecimenMatchPairing other)
        {
            if (ReferenceEquals(null, other))
            {
                return false;
            }

            if (ReferenceEquals(this, other))
            {
                return true;
            }

            return ReferenceLaboratoryNumber == other.ReferenceLaboratoryNumber &&
                   NotificationId == other.NotificationId;
        }

        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj))
            {
                return false;
            }

            if (ReferenceEquals(this, obj))
            {
                return true;
            }

            if (obj.GetType() != GetType())
            {
                return false;
            }

            return Equals((SpecimenMatchPairing)obj);
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(ReferenceLaboratoryNumber, NotificationId);
        }

        public static bool operator ==(SpecimenMatchPairing left, SpecimenMatchPairing right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SpecimenMatchPairing left, SpecimenMatchPairing right)
        {
            return !Equals(left, right);
        }

        #endregion
    }
}
