using System;

namespace ntbs_service.DataMigration.RawModels
{
    // ReSharper disable once ClassNeverInstantiated.Global
    // MigrationNotificationsView
    public class MigrationDbNotification : MigrationDbRecord
    {
        public string Source { get; set; }
        public Guid? NtbsHospitalId { get; set; }
        public string EtsId { get; set; }
        public string LtbrId { get; set; }
        public string LtbrPatientId { get; set; }
        public string GroupId { get; set; }
        public DateTime? NotificationDate { get; set; }
        public int? IsDenotified { get; set; }
        public DateTime? DenotificationDate { get; set; }
        public string HivTestStatus { get; set; }
        public string Consultant { get; set; }
        public string CaseManager { get; set; }
        public string Notes { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string Postcode { get; set; }
        public string FamilyName { get; set; }
        public string GivenName { get; set; }
        public string NhsNumber { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public bool UkBorn { get; set; }
        public int? BirthCountryId { get; set; }
        public int? UkEntryYear { get; set; }
        public int? NtbsEthnicGroupId { get; set; }
        public int? NtbsSexId { get; set; }
        public int? NhsNumberNotKnown { get; set; }
        public int? NoFixedAbode { get; set; }
        public int? NtbsOccupationId { get; set; }
        public string OccupationFreetext { get; set; }
        public string LocalPatientId { get; set; }
        public DateTime? DeathDate { get; set; }
        public string HasVisitor { get; set; }
        public int? visitor_Country1 { get; set; }
        public int? visitor_Country2 { get; set; }
        public int? visitor_Country3 { get; set; }
        public string visitor_TotalNumberOfCountries { get; set; }
        public int? visitor_StayLengthInMonths1 { get; set; }
        public int? visitor_StayLengthInMonths2 { get; set; }
        public int? visitor_StayLengthInMonths3 { get; set; }
        public string HasTravel { get; set; }
        public int? travel_Country1 { get; set; }
        public int? travel_Country2 { get; set; }
        public int? travel_Country3 { get; set; }
        public string travel_TotalNumberOfCountries { get; set; }
        public int? travel_StayLengthInMonths1 { get; set; }
        public int? travel_StayLengthInMonths2 { get; set; }
        public int? travel_StayLengthInMonths3 { get; set; }
        public DateTime? SymptomOnsetDate { get; set; }
        public int? IsSymptomatic { get; set; }
        public DateTime? FirstPresentationDate { get; set; }
        public string HealthcareSetting { get; set; }
        public string HealthcareDescription { get; set; }
        public DateTime? FirstHomeVisitDate { get; set; }
        public string HomeVisitCarriedOut { get; set; }
        public DateTime? TbServicePresentationDate { get; set; }
        public DateTime? DiagnosisDate { get; set; }
        public DateTime? StartOfTreatmentDate { get; set; }
        public int? DidNotStartTreatment { get; set; }
        public int? IsPostMortem { get; set; }
        public string TreatmentRegimen { get; set; }
        public DateTime? MDRTreatmentStartDate { get; set; }
        public string DotStatus { get; set; }
        public string IsDotOffered { get; set; }
        public string EnhancedCaseManagementStatus { get; set; }
        public string BCGVaccinationState { get; set; }
        public int? BCGVaccinationYear { get; set; }
        public string DiabetesStatus { get; set; }
        public string HepatitisBStatus { get; set; }
        public string HepatitisCStatus { get; set; }
        public string LiverDiseaseStatus { get; set; }
        public string RenalDiseaseStatus { get; set; }
        public string ImmunosuppressionStatus { get; set; }
        public int? HasBioTherapy { get; set; }
        public int? HasTransplantation { get; set; }
        public int? HasOther { get; set; }
        public string OtherDescription { get; set; }
        public string ImmigrationDetaineeStatus { get; set; }
        public string AsylumSeekerStatus { get; set; }
        public string AlcoholMisuseStatus { get; set; }
        public string SmokingStatus { get; set; }
        public string MentalHealthStatus { get; set; }
        public string riskFactorDrugs_Status { get; set; }
        public int? riskFactorDrugs_IsCurrent { get; set; }
        public int? riskFactorDrugs_InPastFiveYears { get; set; }
        public int? riskFactorDrugs_MoreThanFiveYearsAgo { get; set; }
        public string riskFactorHomelessness_Status { get; set; }
        public int? riskFactorHomelessness_IsCurrent { get; set; }
        public int? riskFactorHomelessness_InPastFiveYears { get; set; }
        public int? riskFactorHomelessness_MoreThanFiveYearsAgo { get; set; }
        public string riskFactorImprisonment_Status { get; set; }
        public int? riskFactorImprisonment_IsCurrent { get; set; }
        public int? riskFactorImprisonment_InPastFiveYears { get; set; }
        public int? riskFactorImprisonment_MoreThanFiveYearsAgo { get; set; }
        public int? AdultsIdentified { get; set; }
        public int? ChildrenIdentified { get; set; }
        public int? AdultsScreened { get; set; }
        public int? ChildrenScreened { get; set; }
        public int? AdultsActiveTB { get; set; }
        public int? ChildrenActiveTB { get; set; }
        public int? AdultsLatentTB { get; set; }
        public int? ChildrenLatentTB { get; set; }
        public int? AdultsStartedTreatment { get; set; }
        public int? ChildrenStartedTreatment { get; set; }
        public int? AdultsFinishedTreatment { get; set; }
        public int? ChildrenFinishedTreatment { get; set; }
        public string PreviouslyHadTb { get; set; }
        public int? PreviousTbDiagnosisYear { get; set; }
        public string PreviouslyTreated { get; set; }
        public int? PreviousTreatmentCountryId { get; set; }
        public string mdr_ExposureToKnownTbCase { get; set; }
        public string mdr_RelationshipToCase { get; set; }
        public string mdr_CaseInUKStatus { get; set; }
        public string mdr_RelatedNotificationId { get; set; }
        public int? mdr_CountryId { get; set; }
    }
}
